sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: M96XJbyu+KnH0bTM0X3tdQ55BfvFvweKn9QkRTKwuAuEtqgs8H8NM5r6579vF3TiHdeKd7YhXAhpPKeznUU3qwVB6ke7mqLr6FNGrIzVJU4OR7SaX5vJThOFc8PM+H0TY+F5NAmJJ4H+rAjM+8n3ZTyZcaQATsIlxuzz/6koShMIx/+1r4FzPMPkScjIdy0ukiXFyNy+emYQ98T2sFkmPmSrSdiYfPbVIwUR6fXz7kfn6DhejoBqaiY+3k7nWoZz+FhYeGbAcF39a9QYEwVZfa+iZoeImgI7KSjLkIDa9+AIFjDI9Xl0aJgLZB8rXmlrGuvscdh8yIqDrMdLPS8fSo7hgJnBOHk0d4LxDNAy6NefzC2vxQzV4hRRyQWYNGXeeHko8ePOVoW14mSXERXuyqL850K96Y2qZvreAdZ/QZNYmLE1e21wNro0OEoQv9SNJUtZEx+awPpGQYyaqG7cUDj3inuNKftSBfXBnTRwkaMbUAve2ZMqr4DSw68AFZHUCM2XXlSHnmW7hH0ERzqXevO0C1WmO1bti3LxBulqApd1UR7KAKznuwX47B//SJJhooS25UqD+RSJZdOzGmdyxmeeYU2aLtPYvG4D6gH38HiAuLqxT6QixodvZ6yBi/6OQUbwvMNxY/08hsSntBFfksZfkVFo3AqLzcJXgwHTa1o=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Uncle-Vanya--Scenes-from-Country-Life-in-Four-Acts_1756
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy